#!/usr/bin/env python

"""
This pre-commit hook for Git checks modified Python modules with Pyflakes and
searches for trailing spaces or tabs.

Thanks to unutbu (http://stackoverflow.com/users/190597/unutbu) for the answer
to this question: http://bit.ly/ph97P1
"""

__author__ = "Benoit Thiell"
__copyright__ = "Copyright 2011, Benoit Thiell"
__license__ = "GPL"
__email__ = "badzil@gmail.com"

import os
import sys

def main():
    """
    Checks your git commit with PyFlakes.
    """
    ok = True
    for filepath in get_modified_files():
        ok = ok and check_with_pyflakes(filepath)
        ok = ok and check_python_syntax(filepath)

    if ok:
        print >> sys.stderr, 'The commit has been verified.'
        sys.exit(0)
    else:
        sys.stdin = open('/dev/tty')
        answer = raw_input('Commit anyway? [N/y] ')
        if answer.strip()[0].lower() == 'y':
            print >> sys.stderr, 'Committing anyway.'
            sys.exit(0)
        else:
            print >> sys.stderr, 'Commit aborted.'
            sys.exit(1)

def check_with_pyflakes(filepath):
    """
    Checks a Python file with pyflakes. Ignores the 'redefinition of unused'
    modules messages as those are often false-positives.
    """
    ok = True
    for line in os.popen('pyflakes %s' % filepath):
        if 'redefinition of unused' not in line:
            print line.strip()
            ok = False
    return ok

def check_python_syntax(filepath):
    """
    Checks Python code for tabs and trailing spaces.
    """
    code = open(filepath).read()
    if '\t' in code:
        print '%s contains tabs.' % filepath
        return False
    elif ' \n' in code:
        print '%s contains trailing spaces.' % filepath
        return False
    return True

def get_modified_files():
    """
    Returns an iterator on the list of modified files.
    """
    for line in os.popen('git status'):
        if line.startswith('#\tmodified:   '):
            modified_file = line.replace('#\tmodified:', '').strip()
            if modified_file.endswith('.py'):
                yield modified_file
        elif line == '# Changes not staged for commit:\n':
            break

if __name__ == '__main__':
    main()
